color0 #46464c
color1 #ffb4ab
color2 #c3c5d8
color3 #c7c5ce
color4 #d8c0ce
color5 #c3c5d8
color6 #c7c5ce
color7 #e5e2e3
color8 #919096
color9 #ffb4ab
color10 #c3c5d8
color11 #c7c5ce
color12 #d8c0ce
color13 #c3c5d8
color14 #c7c5ce
color15 #e5e2e3

cursor                #e5e2e3
cursor_text_color     #131314
background            #131314
foreground            #e5e2e3
selection_foreground  #c7c6cc
selection_background  #46464c
active_border_color   #c3c5d8
inactive_border_color #46464c
url_color             #c3c5d8

active_tab_foreground   #2d303e
active_tab_background   #c3c5d8
inactive_tab_foreground #c7c6cc
inactive_tab_background #46464c
cursor_trail_color      #c7c6cc
