require("keybinds")
require("animations")
require("rules")
require("input")
require("autostart")
require("env")
require("decoration")
require("layouts")
require("misc")
require("noctalia").apply_theme()
-- uncomment this if you are gonna use nwg-displays
-- require("monitors")
