-- Generated by nwg-displays on 2026-08-04 at 12:15:42. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@165.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "sunshine",
    mode = "1180x820@60.0",
    position = "1920x431",
    scale = 1.0
})
