-- Generated by nwg-displays on 2026-08-16 at 22:37:05. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@165.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "sunshine",
    mode = "2420x1668@60.0",
    position = "1920x705",
    scale = 2.0
})
