-- Generated by nwg-displays on 2026-08-04 at 11:11:54. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-2",
    default = true,
    default_name = "web"
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-2",
    default_name = "dc"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-2",
    default_name = "term"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-2",
    default_name = "game"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "sunshine",
    default = true
})
